name: Walls
main: WallsPlugin.mcLoc.pokuit.georgep.Main
version: 1.2
depend: [WorldEdit]
commands:
   arena:
      description: Set arena
      usage: /<command> <hero>
      permission: superHero.admin
      permission-message: You don't have permission to run this command