name: macroCommands
main: uk.co.georgep.macroCommands.Main
version: 1.0
commands:
   macro:
      description: Macro Maker
      usage: /macro <set/add/remove/run> <name> <optional commands>
      permission: shrapScary.basic
      permission-message: You don't have <permission>