name: Rainbow
main: rainbow.aidan818.adventureanya.pokuit.georgep.Main
version: 1.2
depend: [WorldEdit]
commands:
   rainbow:
      description: Wool Rainbow!
      usage: /<command>
      permission: rainbow.admin
      permission-message: You don't have permission to run this command