name: SuperVanish
main: superVanish.regiusCraft.pokuit.Main
version: 2.0
commands:
   sv:
      description: Super Vanish!
      usage: /<command>
      permission: superVanish.admin
      permission-message: You don't have permission to run this command
   supervanish:
      description: Super Vanish!
      usage: /<command>
      permission: superVanish.admin
      permission-message: You don't have permission to run this command
   fp:
      description: Super Vanish!
      usage: /<command>
      permission: superVanish.admin
      permission-message: You don't have permission to run this command
   fakePlayer:
      description: Super Vanish!
      usage: /<command>
      permission: superVanish.admin
      permission-message: You don't have permission to run this command
      